### ISSUE TITLE
Update XNK

### ISSUE THREAD

**Issue by rickyyean** [PublicDatasets/token-whitepapers#3]
action: Update

criteria: (2) Preference for the latest version of the whitepaper

proof: This is the version 9 of the whitepaper, which is newer than the version 5

data (this is the data you want to update/remove): XNK, Ink Protocol, https://paywithink.com/wp-content/uploads/2018/07/Ink_Protocol_Whitepaper_V9_Listia_Inc.pdf

**Comment by yyw** [comment]
Updated

**Comment by sushiogoto** [comment]
👍

**Comment by sushiogoto** [comment]
:shipit:
