### ISSUE TITLE
Add MEDX (MediBloc)

### ISSUE THREAD

**Issue by sushiogoto** [PublicDatasets/token-whitepapers#5]
Our tracker uses MEDX as the symbol for MediBloc, noticed that MED already exists—adding a duplicate row with the different ticker here.
**USE THIS TEMPLATE TO ADD**

symbol: MEDX

name: MediBloc

url: https://medibloc-homepage.oss-us-west-1.aliyuncs.com/whitepaper/medibloc_whitepaper_en.pdf

**Comment by yyw** [comment]
Added this as a PR
